### ISSUE TITLE
Fix Internet Explorer and Safari formatting

### ISSUE THREAD

**Issue by hubyeti** [ltvch/github-for-developers-7#2]
We need to fix the position of the photo in relation to the individual bio in both IE and Safari.

**Comment by ltvch** [comment]
Its position 
1. Item 1
2. Item 2
3. Item 3

**Comment by ltvch** [comment]
#1 Class goals
-[] My test

**Comment by ltvch** [comment]
#1 Class Goals
-[ ]-

**Comment by ltvch** [comment]
- My check

@mymail
